import { Router } from "express";
import authRouter from "./auth";
import orderRouter from "./order";
import homeRouter from "./home";
import profileRouter from "./profile";
import { authenticated } from "../../middlewares/authenticated";
import { authorizeRoles } from "../../middlewares/authorized";
// import walletRouter from "./userWallets";
const router = Router();
router.use("/home", homeRouter);
router.use(authenticated,authorizeRoles("user"));
router.use("/profile", profileRouter);
router.use("/auth", authRouter);
router.use("/order", orderRouter);
// router.use("/wallet", walletRouter);
export default router;