import { Router } from "express";
import authRouter from "./auth";
import orderRouter from "./order";
import homeRouter from "./home";
import profileRouter from "./profile";
import cartRouter from "./cart";
import user_walletsRouter from "./user_wallets";
import addressRouter from "./address";
import { authenticated } from "../../middlewares/authenticated";
import { authorizeRoles } from "../../middlewares/authorized";
// import walletRouter from "./userWallets";
import favlistRouter from "./favlist";
import restaurantFeaturesRouter from "./restaurantFeatures";

const router = Router();
router.use("/restaurants", restaurantFeaturesRouter);
router.use("/home", homeRouter);
router.use("/auth", authRouter);
router.use(authenticated,authorizeRoles("user"));
router.use("/profile", profileRouter);
router.use("/order", orderRouter);
router.use("/address", addressRouter);
router.use("/cart", cartRouter);
router.use("/favlist", favlistRouter);
router.use("/wallet", user_walletsRouter);
export default router;